apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-cosi-driver

commonAnnotations:
  cosi.storage.k8s.io/authors: "Kubernetes Authors"
  cosi.storage.k8s.io/license: "Apache V2"
  cosi.storage.k8s.io/support: "https://github.com/kubernetes-sigs/container-object-storage-api"

commonLabels:
  app.kubernetes.io/part-of: container-object-storage-interface
  app.kubernetes.io/component: driver-sample
  app.kubernetes.io/version: main
  app.kubernetes.io/name: cosi-driver-sample

resources:
  - deployment.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml
