---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectstorage-provisioner
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-sample
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-sample
spec:
  replicas: 1
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/component: driver-sample
      app.kubernetes.io/version: main
      app.kubernetes.io/name: cosi-driver-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/component: driver-sample
        app.kubernetes.io/version: main
        app.kubernetes.io/name: cosi-driver-sample
    spec:
      serviceAccountName: objectstorage-provisioner-sa
      volumes:
      - name: socket
        emptyDir: {}
      containers:
        - name: cosi-driver
          image: $(DRIVER_IMAGE_ORG)/sample-cosi-driver:$(DRIVER_IMAGE_VERSION)
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
        - name: objectstorage-provisioner-sidecar
          image: $(PROVISIONER_IMAGE_ORG)/objectstorage-sidecar:$(PROVISIONER_IMAGE_VERSION)
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
