---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-sample
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-sample
rules:
  - apiGroups:
      - objectstorage.k8s.io
    resources:
      - buckets
      - bucketclaims
      - bucketaccesses
      - bucketaccessclasses
      - buckets/status
      - bucketclaims/status
      - bucketaccesses/status
      - bucketaccessclasses/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch
  - apiGroups: 
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
    verbs:
      - create
      - get
      - update
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectstorage-provisioner-role-binding
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-sample
    app.kubernetes.io/version: main
    app.kubernetes.io/name: cosi-driver-sample
subjects:
  - kind: ServiceAccount
    name: objectstorage-provisioner-sa
    namespace: default # must set to default. see https://github.com/kubernetes-sigs/kustomize/issues/1377#issuecomment-694731163
roleRef:
  kind: ClusterRole
  name: objectstorage-provisioner-role
  apiGroup: rbac.authorization.k8s.io
