---
apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cosi-driver-sample
  ports:
    - name: s3
      protocol: TCP
      port: 80
      targetPort: 80
    - name: s3-secure
      protocol: TCP
      port: 443
      targetPort: 443
