apiVersion: v1
kind: Service
metadata:
  name: {{ include "driver.fullname" . }}
  labels:
    {{- include "driver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: s3
      protocol: TCP
      name: http
  selector:
    {{- include "driver.selectorLabels" . | nindent 4 }}
